name: Docs Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'docs-site/**'
      - '.github/**'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
        
    - name: Checkout
      uses: actions/checkout@main
      
    - name: install lib dependencies
      run: npm ci

    - name: build lib
      run: npm run build

    - name: install docs dependencies
      run: npm ci
      working-directory: ./docs-site

    - name: build docs
      run: npm run build
      working-directory: ./docs-site
      
    - name: deploy
      run: |
        git init 
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add -A
        git commit -m "deploy"
        git push -f https://${{secrets.ACCESS_TOKEN}}@github.com/MikesGlitch/vue-griddy.git master:gh-pages
      working-directory: ./docs-site/docs/.vuepress/dist   
   
