name: Vuepress Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/**'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    
    - name: Checkout
      uses: actions/checkout@main
       
    - name: install
      run: npm ci
      working-directory: ./docs
      
    - name: build
      run: npm run build
      working-directory: ./docs
      
     #   git init 
     #   git push -f git@github.com:MikesGlitch/vue-griddy.git main:gh-pages
    - name: deploy
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A  
        git commit -m "deploy"
        git push origin gh-pages
      working-directory: ./docs/src/.vuepress/dist   
